#!/bin/bash
set -e

echo "Build hook"
docker build \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VCS_URL=`git config --get remote.origin.url` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=`git rev-parse HEAD` \
  -t $IMAGE_NAME .